((title     "Factorio noob speedrun")
 (category  "any% duo")
 (attempts  9)
 (completed 2)
 (split_names (
   power mall red/green labs blue bots GC purple yellow silo rocket))
 (golds (
   ((title power)     (duration 0.247))
   ((title mall)      (duration 0.265))
   ((title red/green) (duration 0.231))
   ((title labs)      (duration 0.240))
   ((title blue)      (duration 0.233))
   ((title bots)      (duration 0.264))
   ((title GC)        (duration 0.232))
   ((title purple)    (duration 0.303))
   ((title yellow)    (duration 9:21.917))
   ((title silo)      (duration 25:14.377))
   ((title rocket)    (duration 10:13.757))))
 (personal_best (
   (attempt 1)
   (splits (
     ((title power)     (time 11.000)   (is_gold false))
     ((title mall)      (time 37.000)   (is_gold false))
     ((title red/green) (time 44.000)   (is_gold false))
     ((title labs)      (time 1:25.000) (is_gold false))
     ((title blue)      (time 1:34.000) (is_gold false))
     ((title bots)      (time 1:42.000) (is_gold false))
     ((title GC)        (time 2:13.000) (is_gold false))
     ((title purple)    (time 2:58.000) (is_gold false))
     ((title yellow)    (time 3:19.000) (is_gold false))
     ((title silo)      (time 3:48.000) (is_gold false))
     ((title rocket)    (time 3:58.000) (is_gold false))))))
 (history ((
   (attempt 8)
   (splits (
     ((title power)     (time 0.247)     (is_gold true))
     ((title mall)      (time 0.512)     (is_gold true))
     ((title red/green) (time 0.743)     (is_gold true))
     ((title labs)      (time 0.983)     (is_gold true))
     ((title blue)      (time 1.216)     (is_gold true))
     ((title bots)      (time 1.480)     (is_gold true))
     ((title GC)        (time 1.712)     (is_gold true))
     ((title purple)    (time 2.015)     (is_gold true))
     ((title yellow)    (time 9:23.932)  (is_gold true))
     ((title silo)      (time 34:38.309) (is_gold true))
     ((title rocket)    (time 44:52.066) (is_gold true))))))))
